### ISSUE TITLE
Panchangam - generation error

### ISSUE THREAD

**Issue by baskar-yahoo** [sanskrit-coders/adyatithi#1]
Namskaram,

I ran into a runtime error when I tried to generate panchangam using below command

./gen_daily_cal.sh Philadelphia 39:95:26 75:16:52 'NA/Philadelphia' 2020 devanagari

See attached below for exact error details.  last few lines of stdout error is  File "C:\ProgramData\Anaconda3\lib\site-packages\jyotisha\panchangam\temporal.py", line 151, in get_angam_float
    lsun = (swe.calc_ut(jd, swe.SUN)[0] - swe.get_ayanamsa(jd)) % 360
TypeError: unsupported operand type(s) for -: 'tuple' and 'float'
error!

[panchangam-master-error.txt](https://github.com/sanskrit-coders/adyatithi/files/5127296/panchangam-master-error.txt)

Once this is successful, I want to enhance Shri Karthikraman's work by generating appointments for all 5 angams for all 365 days for any given calendar year that can be imported into say google calender. Prior to that, I need to cross the immediate bottleneck as explained above.

**Comment by karthikraman** [comment]
I think this is because of https://github.com/sanskrit-coders/jyotisha/issues/40 -- you can use an older version of swisseph or fix the `calc_ut`
