### ISSUE TITLE
migrator.py broken?

### ISSUE THREAD

**Issue by karthikraman** [sanskrit-coders/adyatithi#2]
migrator.py is still necessary as the code still uses the legacy files for computation. It could be retired once https://github.com/sanskrit-coders/jyotisha/issues/17 is fixed.

There are some benefits to the mega file, in terms of book-keeping and across-the-board fixes, although efficiency is decidedly poor.

**Comment by vvasuki** [comment]
> There are some benefits to the mega file, in terms of book-keeping and across-the-board fixes, although efficiency is decidedly poor.

Why? Multi-file search and replace solutions exist. Doesn't seem to be a good excuse to keep the big file at the expense of delaying issue 17.

**Comment by karthikraman** [comment]
Yeah, not much of an excuse :). But the code still uses these files, so any corrections till I get around to  sanskrit-coders/jyotisha#17 have to be made to the "legacy" files. Sorry, haven't been able to put in much time. Thanks for all the nice edits today! Code is really getting cleaned up thanks to you...
